# Generated by Django 5.0.1 on 2024-01-15 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Product',
            fields=[
                ('carproductid', models.IntegerField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=55)),
                ('Luggage', models.IntegerField()),
                ('Doors', models.IntegerField()),
                ('Passenger', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='car_product/')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
