# Generated by Django 5.0.1 on 2024-02-07 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_product',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='car_product',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='car_product',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Approved', 'Approved'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled')], default='Pending', max_length=20),
        ),
    ]
