# Generated by Django 5.0.1 on 2024-02-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentifyapp', '0002_car_product_end_date_car_product_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent_Car_Details',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('license_number', models.CharField(max_length=100)),
                ('issuing_state', models.CharField(max_length=100)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('pickup_location', models.CharField(max_length=255)),
                ('return_location', models.CharField(max_length=255)),
                ('pickup_date_time', models.DateTimeField()),
                ('return_date_time', models.DateTimeField()),
                ('additional_driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_driver_license', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_driver_dob', models.DateField(blank=True, null=True)),
                ('insurance_policy_number', models.CharField(max_length=100)),
                ('insurance_provider', models.CharField(max_length=100)),
                ('special_requests', models.TextField(blank=True)),
            ],
        ),
    ]
