# Generated by Django 5.0.1 on 2024-02-19 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentifyapp', '0004_rentalrequest_delete_rent_car_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='carproductid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentifyapp.car_product'),
        ),
    ]
